[package]
name = "gig"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
description = "Generate .gitignore files from GitHub's template collection"

[dependencies]
pico-args = "0.5"
include_dir = "0.7"
